#!/usr/bin/env python3
"""
Unit tests for the pure Python parts of dcc.

Run with: python3 tests/python_unit_tests.py   (also run by "make check" and tests/do_tests.sh)

These complement the end-to-end tests run by tests/do_tests.sh, which compile
and run programs with dcc and compare its output against expected output.
"""

import contextlib
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile
import types
import unittest
from unittest import mock

TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(TESTS_DIR)
sys.path.insert(0, os.path.join(ROOT_DIR, "run_time_python"))
sys.path.insert(0, os.path.join(ROOT_DIR, "compile_time_python"))
# version.py is generated by the Makefile
sys.modules.setdefault("version", types.SimpleNamespace(VERSION="unit-tests"))  # type: ignore[arg-type]

# pylint: disable=wrong-import-position
import compile as dcc_compile
import compiler_explanations
import explain_compiler_output
import explain_context
import explain_error
import explain_output_difference
import options
import util


def no_color(text, *_args, **_kwargs):
    return text


class CReprTests(unittest.TestCase):
    """c_repr turns a Python string into a C string literal for the embedded C code"""

    def test_plain(self):
        self.assertEqual(dcc_compile.c_repr("abc"), '"abc"')

    def test_escapes(self):
        self.assertEqual(dcc_compile.c_repr('a"b\\c?'), r'"a\"b\\c\?"')

    def test_control_and_non_ascii_characters(self):
        # octal escapes are used because a digit can safely follow them
        self.assertEqual(dcc_compile.c_repr("x\n\té1"), r'"x\012\011\303\2511"')

    def test_undecodable_filesystem_bytes(self):
        # Python represents undecodable bytes in paths and argv as lone surrogates
        self.assertEqual(dcc_compile.c_repr(os.fsdecode(b"\xff")), r'"\377"')

    @unittest.skipUnless(shutil.which("clang"), "clang not available")
    def test_round_trip_through_clang(self):
        strings = [
            "plain",
            'q"uote',
            "back\\slash",
            "tri??=graph",
            "new\nline",
            "café \U0001f600",
            "é123",
        ]
        source = "#include <stdio.h>\nint main(void) {\n"
        for s in strings:
            source += f"    fputs({dcc_compile.c_repr(s)}, stdout); putchar(0);\n"
        source += "    return 0;\n}\n"
        with tempfile.TemporaryDirectory() as d:
            executable = os.path.join(d, "a.out")
            command = ["clang", "-Wall", "-Wextra", "-Wtrigraphs", "-Werror", "-x", "c", "-", "-o", executable]
            p = subprocess.run(command, input=source, text=True, capture_output=True, check=False)
            self.assertEqual(p.returncode, 0, p.stderr)
            output = subprocess.run([executable], capture_output=True, check=True).stdout
        self.assertEqual(output.split(b"\0")[:-1], [s.encode("utf-8") for s in strings])


class EmbeddingTests(unittest.TestCase):
    """helpers used to embed files and the second executable in the compiled program"""

    def test_the_object_cache_key_ignores_where_the_object_is_written(self):
        # the object goes to a new temporary directory on every compilation,
        # so including its pathname would mean the cache never hit
        command = ["clang", "-c", "-x", "c", "-", "-o", "/tmp/one/w.o", "-O3"]
        self.assertEqual(
            dcc_compile.command_without_output_pathname(command),
            ["clang", "-c", "-x", "c", "-", "-O3"],
        )

    def test_the_object_cache_key_follows_what_was_compiled(self):
        fake_options = types.SimpleNamespace(
            clang_version="19.1.7", debug=0, debug_print=lambda *a, **k: None
        )
        command = ["clang", "-c", "-", "-o", "/tmp/a/w.o", "-O3"]
        key = dcc_compile.wrapper_object_cache_pathname(fake_options, "source", command)
        self.assertIsNotNone(key)
        # the same compilation in a different temporary directory is the same
        elsewhere = ["clang", "-c", "-", "-o", "/tmp/b/w.o", "-O3"]
        self.assertEqual(
            key, dcc_compile.wrapper_object_cache_pathname(fake_options, "source", elsewhere)
        )
        # a different source, option or compiler version is not
        for other in [
            dcc_compile.wrapper_object_cache_pathname(fake_options, "other", command),
            dcc_compile.wrapper_object_cache_pathname(
                fake_options, "source", ["clang", "-c", "-", "-o", "/tmp/a/w.o", "-O0"]
            ),
        ]:
            self.assertNotEqual(key, other)
        fake_options.clang_version = "18.1.0"
        self.assertNotEqual(
            key, dcc_compile.wrapper_object_cache_pathname(fake_options, "source", command)
        )

    def test_the_object_cache_can_be_turned_off(self):
        fake_options = types.SimpleNamespace(
            clang_version="19.1.7", debug=0, debug_print=lambda *a, **k: None
        )
        with mock.patch.dict(os.environ, {"DCC_NO_WRAPPER_CACHE": "1"}):
            self.assertIsNone(
                dcc_compile.wrapper_object_cache_pathname(fake_options, "s", ["clang", "-c"])
            )

    def test_minify_removes_only_comment_lines(self):
        source = b"# comment\nx = 1  # trailing comment kept\n    # indented comment\ny = '#'\n"
        self.assertEqual(dcc_compile.minify(source), b"x = 1  # trailing comment kept\ny = '#'\n")

    def test_linker_reports_missing_main(self):
        gnu_ld = "/usr/bin/ld: x.o: in function `_start':\n(.text+0x1b): undefined reference to `main'\n"
        lld = "ld.lld: error: undefined symbol: main\n>>> referenced by crt1.o\n"
        self.assertTrue(dcc_compile.linker_reports_missing_main(gnu_ld))
        self.assertTrue(dcc_compile.linker_reports_missing_main(lld))
        self.assertFalse(dcc_compile.linker_reports_missing_main("x.c:(.text+0x10): undefined reference to `main_menu'"))
        self.assertFalse(dcc_compile.linker_reports_missing_main("ld.lld: error: undefined symbol: mainloop\n"))

    def test_linker_reports_renamed_function(self):
        c = "/usr/bin/ld: x.o: undefined reference to `__renamed_read'\n"
        lld = "ld.lld: error: undefined symbol: __renamed_read\n"
        # ld demangles C++, so the renamed name is not alone after the backtick
        demangled = "/usr/bin/ld: x.o: undefined reference to `std::istream::__renamed_read(char*, long)'\n"
        template = "/usr/bin/ld: undefined reference to `std::basic_istream<char, std::char_traits<char> >::__renamed_read(char*, long)'\n"
        lld_demangled = "ld.lld: error: undefined symbol: std::basic_ostream<char, std::char_traits<char> >::__renamed_write(char const*, long)\n"
        self.assertTrue(dcc_compile.linker_reports_renamed_function(c))
        self.assertTrue(dcc_compile.linker_reports_renamed_function(lld))
        self.assertTrue(dcc_compile.linker_reports_renamed_function(demangled))
        self.assertTrue(dcc_compile.linker_reports_renamed_function(template))
        self.assertTrue(dcc_compile.linker_reports_renamed_function(lld_demangled))
        self.assertFalse(dcc_compile.linker_reports_renamed_function("undefined reference to `read'\n"))
        self.assertFalse(dcc_compile.linker_reports_renamed_function("__renamed_read is fine\n"))


class CleanCSourceTests(unittest.TestCase):
    """clean_c_source removes literals and comments before variables are extracted from a line"""

    def test_string_literals_removed(self):
        self.assertEqual(util.clean_c_source('printf("%d\\n", a[i]);'), "printf(, a[i]);\n")

    def test_escaped_quotes_inside_string(self):
        self.assertEqual(util.clean_c_source('printf("say \\"hi\\" %d", a[i]);'), "printf(, a[i]);\n")

    def test_string_ending_in_escaped_backslash(self):
        self.assertEqual(util.clean_c_source('printf("a\\\\", a[i], "b");'), "printf(, a[i], );\n")

    def test_character_literals(self):
        self.assertEqual(util.clean_c_source("c = '\\''; d = '\"'; e = a[i];"), "c = ; d = ; e = a[i];\n")

    def test_comments_removed(self):
        self.assertEqual(util.clean_c_source("x = a[i]; // it's a comment"), "x = a[i];\n")
        self.assertEqual(util.clean_c_source("x = a[i]; /* comment */"), "x = a[i];\n")


class SourceLineTests(unittest.TestCase):
    """fileline and Location.surrounding_source show the source around an error"""

    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.filename = os.path.join(self.temp_dir.name, "prog.c")
        self.write_source("int main(void) {\n    int a[10] = {0};\n    return a[10];\n}\n")

    def tearDown(self):
        self.temp_dir.cleanup()

    def write_source(self, source):
        with open(self.filename, "w", encoding="utf-8") as f:
            f.write(source)
        util.cached_source_files.clear()

    def test_lines_are_numbered_from_one(self):
        self.assertEqual(util.fileline(self.filename, 1), "int main(void) {\n")
        self.assertEqual(util.fileline(self.filename, 4), "}\n")

    def test_line_numbers_outside_the_file_give_nothing(self):
        self.assertEqual(util.fileline(self.filename, 0), "")
        self.assertEqual(util.fileline(self.filename, -1), "")
        self.assertEqual(util.fileline(self.filename, 5), "")
        self.assertEqual(util.fileline(os.path.join(self.temp_dir.name, "missing.c"), 1), "")

    def test_surrounding_source_marks_the_error_line(self):
        lines = util.Location(self.filename, 3).surrounding_source(no_color, markMiddle=True)
        expected = ["int main(void) {\n", "    int a[10] = {0};\n", "--> return a[10];\n", "}\n"]
        self.assertEqual(lines, expected)

    def test_error_on_line_1_does_not_show_the_end_of_the_file(self):
        self.write_source("int main(void) { int a[1]; return a[1]; }\n    // trailing comment\n")
        lines = util.Location(self.filename, 1).surrounding_source(no_color, markMiddle=True)
        self.assertEqual(lines, ["-->int main(void) { int a[1]; return a[1]; }\n", "    // trailing comment\n"])

    def test_one_line_program_still_has_source_for_variables(self):
        self.write_source("int main(void) { int a[1]; return a[1]; }\n")
        lines = util.Location(self.filename, 1).surrounding_source(no_color, clean=True)
        self.assertEqual(lines, ["int main(void) { int a[1]; return a[1]; }\n"])


class CompilerMessageParsingTests(unittest.TestCase):
    """get_next_message splits compiler output into messages"""

    CLANG_OUTPUT = (
        "prog.c:4:11: warning: format specifies type 'int *' but the argument has type 'int' [-Wformat]\n"
        '    scanf("%d", i);\n'
        "           ~~   ^\n"
        "prog.c:9:5: error: use of undeclared identifier 'count'\n"
        "    count++;\n"
        "    ^\n"
        "1 warning and 1 error generated.\n"
    )

    def test_messages_are_split_and_parsed(self):
        lines = self.CLANG_OUTPUT.splitlines()
        message, lines = explain_compiler_output.get_next_message(lines)
        self.assertEqual((message.file, message.line_number, message.column, message.type), ("prog.c", "4", "11", "warning"))
        self.assertEqual(message.highlighted_word, "i")
        self.assertEqual(message.underlined_word, "%d")
        message, lines = explain_compiler_output.get_next_message(lines)
        self.assertEqual((message.line_number, message.type, message.highlighted_word), ("9", "error", "count"))
        self.assertEqual(lines, [])

    def test_notes_are_kept_separately(self):
        output = (
            "prog.c:3:5: error: call to undeclared function 'f'\n"
            "    f();\n"
            "    ^\n"
            "prog.c:1:6: note: 'g' declared here\n"
            "void g(void);\n"
            "     ^\n"
        )
        message, lines = explain_compiler_output.get_next_message(output.splitlines())
        self.assertEqual(message.text, output.splitlines()[:3])
        self.assertEqual(message.note, output.splitlines()[3:])
        self.assertEqual(lines, [])


class CompilerOutputTests(unittest.TestCase):
    """explain_compiler_output prints the compiler's messages with explanations"""

    class Args:  # the options explain_compiler_output uses
        colorize_output = False
        debug = 0
        max_explanations = 3
        compile_helper = ""

    def output_for(self, compiler_output):
        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr):
            explain_compiler_output.explain_compiler_output(compiler_output, self.Args())
        return stderr.getvalue()

    def test_no_escape_codes_without_colour(self):
        with_note = (
            "prog.c:3:5: warning: variable 'x' is uninitialized when used here [-Wuninitialized]\n"
            "    return x;\n"
            "           ^\n"
            "prog.c:2:10: note: initialize the variable 'x' to silence this warning\n"
            "    int x;\n"
            "         ^\n"
            "          = 0\n"
            "1 warning generated.\n"
        )
        gcc_quotes = "prog.c:3:13: warning: ‘a’ is used uninitialized [-Wuninitialized]\n    3 |     return a[0];\n"
        for compiler_output in [with_note, gcc_quotes]:
            output = self.output_for(compiler_output)
            self.assertIn("dcc explanation:", output)
            self.assertNotIn("\x1b", output)

    def test_a_repeated_include_chain_is_collapsed(self):
        # a cyclic #include makes the compiler repeat the chain ~100 times
        chain = (
            "In file included from prog.c:1:\nIn file included from ./prog.h:1:\n" * 100
        )
        output = self.output_for(
            chain + "./prog.h:1:10: error: #include nested too deeply\n"
        )
        self.assertEqual(output.count("In file included from"), 2)
        self.assertIn("# previous 2 lines repeated 99 more times", output)
        self.assertIn("#include nested too deeply", output)

    def test_an_unrepeated_include_chain_is_left_alone(self):
        chain = (
            "In file included from prog.c:1:\n"
            "In file included from ./a.h:1:\n"
            "In file included from ./b.h:1:\n"
        )
        output = self.output_for(
            chain + "./c.h:1:22: error: use of undeclared identifier 'x'\n"
        )
        self.assertEqual(output.count("In file included from"), 3)
        self.assertNotIn("# previous", output)

    def test_a_system_header_note_after_an_include_chain_is_not_printed(self):
        # the chain line leaves the note leading its own message
        output = self.output_for(
            "prog.c:5:5: warning: argument 1 null where non-null expected [-Wnonnull]\n"
            "    5 |     fgetc(f);\n"
            "      |     ^~~~~~~~\n"
            "In file included from prog.c:1:\n"
            "/usr/include/stdio.h:575:12: note: in a call to function 'fgetc'"
            " declared 'nonnull'\n"
            "  575 | extern int fgetc (FILE *__stream) __nonnull ((1));\n"
            "      |            ^~~~~\n"
        )
        self.assertIn("In file included from prog.c:1:", output)
        self.assertNotIn("/usr/include/stdio.h", output)
        self.assertNotIn("__nonnull", output)


class RuntimeExplanationTests(unittest.TestCase):
    """explanations of signals"""

    def test_stack_overflow_and_abort(self):
        import signal as signals  # pylint: disable=import-outside-toplevel

        with mock.patch.dict(os.environ, {"DCC_STACK_OVERFLOW": "1"}):
            self.assertIn("infinite recursion", explain_error.explain_signal(signals.SIGSEGV))
        with mock.patch.dict(os.environ, {}, clear=False):
            os.environ.pop("DCC_STACK_OVERFLOW", None)
            self.assertIn("invalid pointer", explain_error.explain_signal(signals.SIGSEGV))
        # abort() is only blamed on assert() when assert() really did call it
        assert_stack = "#15 0x7f in __assert_fail_base () at ./assert/assert.c:118"
        self.assertIn("assert", explain_error.explain_signal(signals.SIGABRT, assert_stack))
        throw_stack = "#14 0x7f in __cxa_throw () from /lib/libstdc++.so.6"
        abort_explanation = explain_error.explain_signal(signals.SIGABRT, throw_stack)
        self.assertIn("exception", abort_explanation)
        self.assertNotIn("assert", abort_explanation)
        self.assertNotIn("assert", explain_error.explain_signal(signals.SIGABRT))

    def test_debug_level_from_environment(self):
        with mock.patch.dict(os.environ, {"DCC_DEBUG": "2"}):
            self.assertEqual(util.debug_level_from_environment(), 2)
        with mock.patch.dict(os.environ, {"DCC_DEBUG": "yes"}):
            self.assertEqual(util.debug_level_from_environment(), 0)


class ExplanationTests(unittest.TestCase):
    """explanations are selected by matching the compiler message"""

    @staticmethod
    def explanation_for(compiler_output):
        message, _ = explain_compiler_output.get_next_message(compiler_output.splitlines())
        return compiler_explanations.get_explanation(message, colorize_output=False)

    def test_undeclared_identifier(self):
        e = self.explanation_for("prog.c:9:5: error: use of undeclared identifier 'count'\n    count++;\n    ^\n")
        self.assertIn("'count'", e.text)
        self.assertIn("without previously declaring it", e.text)

    def test_scanf_missing_ampersand(self):
        e = self.explanation_for(CompilerMessageParsingTests.CLANG_OUTPUT)
        self.assertEqual(e.label, "scanf_missing_ampersand")
        self.assertIn("forgotten an '&' before 'i'", e.text)

    def test_gcc_uninitialized_variable_wording(self):
        # gcc uses smart quotes and dropped "in this function" from the message in gcc 10
        e = self.explanation_for("prog.c:3:13: warning: ‘a’ is used uninitialized [-Wuninitialized]\n    3 |     return a[0];\n")
        self.assertEqual(e.label, "uninitialized-local-variable")

    def test_colours_are_used_only_when_asked_for(self):
        # a helper script is given the explanation as plain text
        message, _ = explain_compiler_output.get_next_message(
            "prog.c:9:5: error: use of undeclared identifier 'count'\n    count++;\n    ^\n".splitlines()
        )
        self.assertNotIn("\x1b", compiler_explanations.get_explanation(message, colorize_output=False).text)
        self.assertIn("\x1b", compiler_explanations.get_explanation(message, colorize_output=True).text)

    def test_unknown_message_has_no_explanation(self):
        self.assertIsNone(self.explanation_for("prog.c:1:1: error: something dcc has never heard of\n"))

    def test_labels_are_unique(self):
        # labels name the files of the extracted compile-time tests
        labels = [e.label for e in compiler_explanations.explanations]
        duplicates = sorted({label for label in labels if labels.count(label) > 1})
        self.assertEqual(duplicates, [])

    def test_every_explanation_has_a_reproduce_program(self):
        missing = [e.label for e in compiler_explanations.explanations if not e.reproduce.strip()]
        self.assertEqual(missing, [])


class OptionsTests(unittest.TestCase):
    """dcc's own command line options and the clang options it inspects"""

    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.old_cwd = os.getcwd()
        os.chdir(self.temp_dir.name)
        with open("prog.c", "w", encoding="utf-8") as f:
            f.write("int main(void) { return 0; }\n")

    def tearDown(self):
        os.chdir(self.old_cwd)
        self.temp_dir.cleanup()

    @staticmethod
    def parse(*args):
        with contextlib.redirect_stderr(io.StringIO()):
            parsed = options.parse_args(list(args))
        parsed.tar.close()
        return parsed

    def test_source_files_and_defaults(self):
        parsed = self.parse("prog.c")
        self.assertEqual(parsed.source_files, {"prog.c"})
        self.assertEqual(parsed.object_pathname, "a.out")
        self.assertFalse(parsed.libraries_being_linked)

    def test_sanitizer_selection(self):
        self.assertEqual(self.parse("-fsanitize=address,valgrind", "prog.c").sanitizers, ["address", "valgrind"])
        with self.assertRaises(SystemExit):
            self.parse("-fsanitize=bogus", "prog.c")

    def test_libraries_other_than_libc_and_libm_are_noticed(self):
        self.assertFalse(self.parse("-lm", "prog.c").libraries_being_linked)
        self.assertTrue(self.parse("-lcurl", "prog.c").libraries_being_linked)
        separated = self.parse("-l", "curl", "prog.c")
        self.assertTrue(separated.libraries_being_linked)
        self.assertEqual(separated.user_supplied_compiler_args[:2], ["-l", "curl"])
        with self.assertRaises(SystemExit):
            self.parse("prog.c", "-l")

    def test_pthreads_is_rewritten_for_gcc(self):
        parsed = self.parse("-pthreads", "prog.c")
        self.assertTrue(parsed.threads_used)
        self.assertIn("-pthread", parsed.user_supplied_compiler_args)
        self.assertNotIn("-pthreads", parsed.user_supplied_compiler_args)

    def test_response_files(self):
        with open("args.rsp", "w", encoding="utf-8") as f:
            f.write('-Wextra "-DGREETING=\\"hi there\\""\nprog.c\n')
        parsed = self.parse("@args.rsp")
        self.assertEqual(parsed.user_supplied_compiler_args, ["-Wextra", '-DGREETING="hi there"', "prog.c"])
        with self.assertRaises(SystemExit):
            self.parse("@missing.rsp")
        with open("bad.rsp", "w", encoding="utf-8") as f:
            f.write('"unbalanced\n')
        with self.assertRaises(SystemExit):
            self.parse("@bad.rsp")

    def test_will_not_overwrite_source_with_executable(self):
        with self.assertRaises(SystemExit):
            self.parse("prog.c", "-o", "prog.c")

    def test_embedded_environment_variable(self):
        parsed = self.parse("--embedded_environment_variable=X=a=b", "prog.c")
        self.assertEqual(parsed.embedded_environment_variables, [("X", "a=b")])


class OutputDifferenceTests(unittest.TestCase):
    """explanations of incorrect output, from the values the C code puts in the environment"""

    @staticmethod
    def explanation(**variables):
        environment = {
            "DCC_EXPECTED_STDOUT": "",
            "DCC_OUTPUT_ERROR": "incorrect output",
            "DCC_ACTUAL_LINE_NUMBER": "1",
            "DCC_N_EXPECTED_BYTES_SEEN": "0",
            "DCC_N_ACTUAL_BYTES_SEEN": "0",
            "DCC_EXPECTED_LINE": "",
            "DCC_ACTUAL_LINE": "",
            "DCC_EXPECTED_COLUMN": "0",
            "DCC_ACTUAL_COLUMN": "0",
        }
        environment.update(variables)
        with mock.patch.dict(os.environ, environment):
            return explain_output_difference.explain_output_difference(no_color)

    def test_too_much_output_reports_a_bound(self):
        text = self.explanation(DCC_OUTPUT_ERROR="too much output", DCC_N_ACTUAL_BYTES_SEEN="95", DCC_ACTUAL_COLUMN="6", DCC_ACTUAL_LINE="line 1")
        self.assertIn("too much output", text)
        self.assertIn("more than 101 bytes", text)

    def test_extra_characters_at_end_of_last_line(self):
        text = self.explanation(DCC_EXPECTED_STDOUT="Hello", DCC_EXPECTED_LINE="Hello", DCC_ACTUAL_LINE="Hello!", DCC_EXPECTED_COLUMN="5", DCC_ACTUAL_COLUMN="5")
        self.assertIn("extra characters at the end of the line", text)
        self.assertNotIn("more characters were expected", text)

    def test_missing_final_newline(self):
        text = self.explanation(DCC_EXPECTED_STDOUT="Hello\n", DCC_EXPECTED_LINE="Hello\n", DCC_ACTUAL_LINE="Hello", DCC_EXPECTED_COLUMN="5", DCC_ACTUAL_COLUMN="5")
        self.assertIn("newline was missing", text)

    def test_missing_last_character(self):
        text = self.explanation(DCC_EXPECTED_STDOUT="Hello!\n", DCC_EXPECTED_LINE="Hello!\n", DCC_ACTUAL_LINE="Hello\n", DCC_EXPECTED_COLUMN="5", DCC_ACTUAL_COLUMN="5")
        self.assertIn("'!' was missing from the end of the output line", text)

    def test_no_output(self):
        text = self.explanation(DCC_EXPECTED_STDOUT="Hello\n", DCC_EXPECTED_LINE="Hello\n")
        self.assertIn("no output", text)

    def test_non_printable_character(self):
        text = self.explanation(DCC_EXPECTED_STDOUT="ab\n", DCC_EXPECTED_LINE="ab\n", DCC_ACTUAL_LINE="a\x10b\n", DCC_EXPECTED_COLUMN="1", DCC_ACTUAL_COLUMN="1")
        self.assertIn("non-printable character", text)
        self.assertIn("\\x10", text)


class ValueDisplayTests(unittest.TestCase):
    """values printed by gdb are rewritten for novices"""

    @staticmethod
    def clarify(value):
        return explain_context.clarify_values(value, no_color, [])

    def test_memory_fill_values_are_labelled_uninitialized(self):
        self.assertEqual(self.clarify(util.MEMORY_FILL["int32"]), "<uninitialized value>")
        self.assertEqual(self.clarify("{" + util.MEMORY_FILL["int32"] + ", 1, 2}"), "{<uninitialized value>, 1, 2}")

    def test_repeated_fill_bytes(self):
        self.assertEqual(self.clarify("'\\252' <repeats 5 times>"), "<5 uninitialized values>")

    def test_null_pointer(self):
        self.assertEqual(self.clarify("0x0"), "NULL")

    def test_extract_expressions(self):
        expressions = explain_context.extract_expressions("a[i] = p->next->data + f(x);")
        self.assertEqual(set(expressions), {"a", "i", "a[i]", "p", "p->next", "p->next->data", "f", "x"})


class TracebackTests(unittest.TestCase):
    """the function call traceback shows the innermost calls and main"""

    @staticmethod
    def frames(n_frames):
        # the innermost n_frames - 1 calls are to f, the outermost is main
        stack = [
            util.Location("prog.c", 10 + i, function="f", params=f"n={i}", frame_number=str(i))
            for i in range(n_frames - 1)
        ]
        return stack + [util.Location("prog.c", 99, function="main", params="", frame_number=str(n_frames - 1))]

    def traceback(self, n_frames, truncated=False):
        return explain_context.explain_stack(self.frames(n_frames), [], no_color, truncated=truncated).splitlines()

    def test_every_call_shown_has_its_call_site(self):
        for n_frames in [2, 3, 10, 11, 12, 13, 50]:
            lines = self.traceback(n_frames)
            for line in lines[:-1]:
                if line != "...":
                    self.assertIn(" called at line ", line, f"{n_frames} frames: {line}")
            self.assertEqual(lines[-1], "main()", f"{n_frames} frames")

    def test_short_stacks_are_shown_in_full(self):
        for n_frames in [1, 2, 10, 11]:
            self.assertEqual(len(self.traceback(n_frames)), n_frames)
            self.assertNotIn("...", self.traceback(n_frames))

    def test_long_stacks_are_shortened_but_keep_main(self):
        lines = self.traceback(50)
        self.assertEqual(len(lines), explain_context.MAX_CALLS_SHOWN + 2)
        self.assertEqual(lines[explain_context.MAX_CALLS_SHOWN], "...")
        self.assertEqual(lines[-1], "main()")

    def test_a_truncated_stack_does_not_pretend_to_show_main(self):
        lines = self.traceback(50, truncated=True)
        self.assertEqual(lines[-1], "...")
        self.assertNotIn("main()", lines)
        self.assertEqual(len(lines), explain_context.MAX_CALLS_SHOWN + 1)

    def test_calls_are_selected_innermost_first_and_in_range(self):
        # get_variable_addresses drives gdb to exactly these frames,
        # so they must be real frames and in the order the traceback shows
        for n_frames, truncated in [(1, False), (3, False), (12, False), (50, False), (5, True), (50, True)]:
            shown = explain_context.shown_calls(n_frames, truncated)
            indexes = [index for index in shown if index is not None]
            self.assertEqual(indexes, sorted(indexes), f"{n_frames} {truncated}")
            self.assertEqual(indexes[0], 0, f"{n_frames} {truncated}")
            for index in indexes:
                self.assertLess(index, n_frames, f"{n_frames} {truncated}")
            self.assertLessEqual(shown.count(None), 1, f"{n_frames} {truncated}")


class StackParsingTests(unittest.TestCase):
    """gdb's backtrace lines are parsed into locations, ignoring library frames"""

    def test_user_frame(self):
        frame = explain_error.parse_gdb_stack_frame("#1  0x0000555555555189 in __real_main (argc=1, argv=0x7ffd) at prog.c:5")
        self.assertEqual((frame.function, frame.filename, frame.line_number, frame.frame_number), ("main", "prog.c", 5, "1"))

    def test_library_frames_are_ignored(self):
        for line in [
            "#0  __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:50",
            "#2  0x00007ffff7 in __libc_start_main () at /usr/lib/libc.c:300",
            "#0  0x00007ffff7e2 in __strlen_avx2 () from /lib/x86_64-linux-gnu/libc.so.6",
            "#5  0x00007ffff7 in _IO_new_file_close_it (fp=0x51) at ./libio/libioP.h:1041",
            "#8  0x00005ed1d8 in _explain_error () at <stdin>:1685",
        ]:
            self.assertIsNone(explain_error.parse_gdb_stack_frame(line), line)

    def test_paths_with_spaces_and_underscored_functions(self):
        # a student's file may be called "assignment 1.c" and their function _f
        for line, expected in [
            ("#13 0x00005ed1d8 in main () at assignment 1.c:4", ("main", "assignment 1.c", 4)),
            ("#13 0x00005ed1d8 in main () at lab 3/prog.c:4", ("main", "lab 3/prog.c", 4)),
            ("#13 0x00005ed1d8 in main () at wei:rd.c:2", ("main", "wei:rd.c", 2)),
            ("#13 0x00005ed1d8 in _f () at min.c:1", ("_f", "min.c", 1)),
            ("#13 0x00005ed1d8 in __f (n=5) at dunder.c:4", ("__f", "dunder.c", 4)),
            ("#13 0x00005ed1d8 in _Deref (n=3) at dunder.c:3", ("_Deref", "dunder.c", 3)),
        ]:
            frame = explain_error.parse_gdb_stack_frame(line)
            self.assertIsNotNone(frame, line)
            self.assertEqual((frame.function, frame.filename, frame.line_number), expected)

    def test_a_stack_with_no_user_source_does_not_fall_back_to_a_library_frame(self):
        # exiting main runs the C library's _dl_call_fini, whose source dcc can
        # not see, so there is no frame it can usefully report
        stack = """#0  0x00007ffff7 in _dl_call_fini (closure_map=0x7ffff7) at ./elf/dl-call_fini.c:43
#1  0x00007ffff7 in _dl_fini () at ./elf/dl-fini.c:120
#2  0x00007ffff7 in __run_exit_handlers (status=0) at ./stdlib/exit.c:108"""
        with mock.patch.object(explain_error.gdb_interface, "gdb_execute", return_value=stack):
            with mock.patch.object(explain_error.gdb_interface, "gdb_set_frame"):
                frames, _, text = explain_error.parse_stack()
        self.assertEqual(frames, [])
        self.assertEqual(text, stack)


class DocumentationTests(unittest.TestCase):
    """the README and the man page state what dcc is and is not for, see issue #97"""

    # topics issue #97 asked about, in whichever order the prose puts them
    TOPICS = ["cross-compilation", "gcc", "slower", "shipped", "security"]

    def test_readme_has_a_scope_section(self):
        with open(os.path.join(ROOT_DIR, "README.md"), encoding="utf-8") as f:
            readme = f.read()
        heading = re.search(r"^# +scope\b.*$", readme, re.IGNORECASE | re.MULTILINE)
        self.assertIsNotNone(heading, "no '# Scope' section")
        rest = readme[heading.end() :]
        next_heading = re.search(r"^# ", rest, re.MULTILINE)
        scope = (rest[: next_heading.start()] if next_heading else rest).lower()
        for topic in self.TOPICS:
            self.assertIn(topic, scope)

    def test_man_page_include_has_a_description(self):
        path = os.path.join(ROOT_DIR, "lib", "help2man_include.txt")
        with open(path, encoding="utf-8") as f:
            include = f.read()
        self.assertTrue("[DESCRIPTION]" in include, "no [DESCRIPTION] section")
        # the section must say something, not just carry the header - issue #100
        description = include.split("[DESCRIPTION]")[1].split("\n[")[0].lower()
        for topic in self.TOPICS:
            self.assertIn(topic, description)


class CompilerSuppliedTextTests(unittest.TestCase):
    """text from the compiler reaches regexes and int(), so it must not be trusted"""

    IMPLICIT_INT = "type specifier missing, defaults to 'int'"

    @staticmethod
    def explanation_for(compiler_output):
        message, _ = explain_compiler_output.get_next_message(
            compiler_output.splitlines()
        )
        return compiler_explanations.get_explanation(message, colorize_output=False)

    def diagnostic(self, source, caret, points_at=None):
        echoed = f"    1 | {source}"
        if points_at is not None:
            caret = " " * (echoed.index(points_at) - len("      | ")) + caret
        return f"t.c:1:1: error: {self.IMPLICIT_INT}\n{echoed}\n      | {caret}\n"

    def test_regex_metacharacters_in_the_highlighted_word(self):
        # an unbalanced [ used to reach re.search unescaped and raise PatternError
        e = self.explanation_for(self.diagnostic("a[b;", "^~~"))
        self.assertIn("a[b", e.text)

    def test_nested_quantifier_in_the_highlighted_word(self):
        # (a*)* used to be compiled as a pattern and backtrack exponentially
        source = "(a*)*p;"
        text = self.diagnostic(source, "^~~~~~") + "    2 | " + "a" * 40 + "\n"
        self.assertIsNotNone(self.explanation_for(text))

    def test_line_number_too_long_for_int(self):
        # Python refuses to convert a string of more than 4300 digits
        nines = "9" * 5000
        output = f"t.c:{nines}:1: error: function definition is not allowed here\n"
        self.assertIsNone(self.explanation_for(output))

    def test_implicit_int_distinguishes_what_was_declared(self):
        for source, points_at, expected in [
            ("counter = 0;", "counter", "type of a variable"),
            ("int add(int b, c) {", "c) {", "type of each function parameter"),
            ("square (int x) {", "square", "return type of a function"),
        ]:
            with self.subTest(source=source):
                e = self.explanation_for(self.diagnostic(source, "^", points_at))
                self.assertIn(expected, e.text)


class CaretColumnTests(unittest.TestCase):
    """the compiler positions its caret by display width, not by character count"""

    def test_narrow_characters_index_unchanged(self):
        self.assertEqual(explain_compiler_output.character_index("abcdef", 3), 3)

    def test_a_wide_character_counts_as_two_columns(self):
        # the second column of a wide character belongs to that character
        line = "\u6210\u7ee9abc"
        self.assertEqual(explain_compiler_output.character_index(line, 4), 2)
        self.assertEqual(explain_compiler_output.slice_by_column(line, 4, 7), "abc")

    def test_column_past_the_end_of_the_line(self):
        self.assertEqual(explain_compiler_output.character_index("ab", 99), 2)
        self.assertEqual(explain_compiler_output.slice_by_column("ab", 99, 99), "")


if __name__ == "__main__":
    unittest.main()
